__________________________________________________________________________

                       Angelfire Communications FTP Server

This FTP server is for uploads by Angelfire's Free Home Page Users only.

    ********************************************************************
    *  NOTICE:  FILES ARE AUTOMATICALLY REMOVED AFTER 15 MINUTES !!!   *
    ********************************************************************

(1) Make sure you're in the "/incoming" directory.

(2) In Netscape, use "File-File Upload" from your pull-down menu to
    initiate the file transfer.  Upload only 1 or 2 files at a time.
    TAKE NOTE of the FILENAME AS LISTED IN our "/incoming" area after
    uploading, since some FTP clients CONVERT FILENAMES TO UPPER CASE !!!
    REMEMBER the names of the files you uploaded, as you will need
    them in the next step.  NOTE UPPER/LOWER CASE of filenames.

(3) After uploading, immediately move your files to your Home Page
    Directory by returning to your "Web Shell" page, typing in the 
    filename you want to activate, and clicking "Activate File".
    Images are activated immediately, but are reviewed over the next
    24 hours.  Images which are corrupt, in the wrong format, or
    inappropriate will be deleted during this review process.
__________________________________________________________________________
